### PR TITLE
remove dist/ folder and tar.gz files

### PR DESCRIPTION
**Pull request by basnijholt**
Keeping binaries inside Git is a bad habit.

They are easily created using
```
python setup.py sdist bdist_wheel
```

and are on PyPI.

@ChristianKuehnel, @usul27, @open-homeautomation, are you guys OK with this?

### CODE REVIEW

**Comment by basnijholt** [comment]
@open-homeautomation, if you add a token called `PYPI_TOKEN` then there is an action I've added that automatically uploads the `sdist` and `wheels` to PyPI.

Or you could give me permissions to add it. Right now, I don't see the "Settings" menu:
image

**Comment by open-homeautomation** [comment]
Let me hand the full repo over to you...

**Comment by open-homeautomation** [comment]
You have to remove or rename your miflora repo first as I can't transfer ownership

**Comment by basnijholt** [comment]
I have renamed mine! 😄

**Comment by open-homeautomation** [comment]
Looks like renaming isn't enough. You need to delete your fork.

**Comment by basnijholt** [comment]
I've deleted it now.

**Comment by open-homeautomation** [comment]
Ok, you should now receive a transfer request

**Comment by basnijholt** [comment]
Amazing! Thanks a lot @open-homeautomation. This is open-source trust at its best! ❤️

**Pull request merged**
